### ISSUE TITLE
fix  sorry bug::'tchannel socket error (ECONNREFUSED from connect): connect ECONNREFUSED',

### ISSUE THREAD

**Issue by tsw424** [uber/tchannel#1208]
client:  ---------------------------------------------------------------------------------------------------------------
for(var i= 0 ; i <5000;i++) {
    var client = TChannel({initTimeout:16000});
    var tchannelJSON = TChannelJSON();
    var clientChan = client.makeSubChannel({
        serviceName: 'server',
        peers: ['127.0.0.1:4040'],
        timeout: 100000
    });
    tchannelJSON.send(clientChan.request({
        headers: {
            cn: 'client'
        },
        serviceName: 'server1',
        hasNoParent: true,
        timeout: 3000,
        timeoutPerAttempt: 1000,
        retryLimit: 2
    }), 'echo', {
        head:   new Date().getTime()
    }, {
        body: 'test'
    }, onResponse);
}

function onResponse(err, resp) {
    var d = resp  ; 
    if (err) {
        console.log('got error', err);
    } else {
        assert.equal(resp.ok, true); 
    }
    console.log(' time ', new Date().getTime() - resp.head.head ); 
}

server: ----------------------------------------------------------------------------------------------------------

var TChannelJSON = require('tchannel/as/json');
var TChannel = require('tchannel');

var server = TChannel({
    serviceName: 'server'
});
var client = TChannel();
var clientChan = client.makeSubChannel({
    serviceName: 'server',
    host: '127.0.0.1:4040'
});

var tchannelJSON = TChannelJSON({
    channel: clientChan
});

var context = {};

tchannelJSON.register(server, 'echo', context, echo);
function echo(context, req, head, body, callback) {
    callback(null, {
        ok:     true,
        head:   head ,
        body:   new Date().getTime() - head.head
    });
}

server.listen(4040, '127.0.0.1', onListening);

function onListening() {

console.log(" server  start  : "+server.hostPort  );
------------------------------------------------------------------------------------------------------------------------------

error-------------------------------------->

got error { [TchannelSocketError: tchannel socket error (ECONNREFUSED from connect): connect ECONNREFUSED]
    console.log(' time ', new Date().getTime() - resp.head.head );
  type: 'tchannel.socket',
                                                     ^
  message: 'tchannel socket error (ECONNREFUSED from connect): connect ECONNREFUSED',
TypeError: Cannot read property 'head' of undefined
  hostPort: null,
    at onResponse (d:\work_sapce_node\kael\test\tchannel\json_client.js:67:54)
  direction: 'out',
  remoteAddr: null,
    at onResponse (d:\work_sapce_node\kael\node_modules\tchannel\as\json.js:122:20)
    at DefinedEvent.onError [as listener] (d:\work_sapce_node\kael\node_modules\tchannel\request.js:127:9)
  name: 'TchannelSocketError',
    at DefinedEvent.emit (d:\work_sapce_node\kael\node_modules\tchannel\lib\event_emitter.js:86:14)
  socketRemoteAddr: '127.0.0.1:4040',
  causeMessage: 'connect ECONNREFUSED',
    at TChannelRequest.emitError (d:\work_sapce_node\kael\node_modules\tchannel\request.js:94:21)
  origMessage: 'connect ECONNREFUSED',
    at onIdentified (d:\work_sapce_node\kael\node_modules\tchannel\request.js:194:25)
  code: 'ECONNREFUSED',
    at finish (d:\work_sapce_node\kael\node_modules\tchannel\peer.js:252:9)
  errno: 'ECONNREFUSED',
    at Array.onConnectionClose (d:\work_sapce_node\kael\node_modules\tchannel\peer.js:239:9)
  syscall: 'connect',
    at DefinedEvent.emit (d:\work_sapce_node\kael\node_modules\tchannel\lib\event_emitter.js:90:25)
  fullType: 'tchannel.socket~!~error.wrapped-io.connect.ECONNREFUSED' }
    at TChannelConnection.resetAll (d:\work_sapce_node\kael\node_modules\tchannel\connection.js:574:21)

**Comment by tsw424** [comment]
timeoutPerAttempt: 330003,


  tchannelJSON.send(clientChan.request({
        headers: {
            cn: 'client'
        },
        serviceName: 'server1',
        hasNoParent: true,
        timeout: 3000,
        timeoutPerAttempt: 330003,
        retryLimit: 2
