### ISSUE TITLE
Installation issue with Node 10 - 13

### ISSUE THREAD

**Issue by congwangeid** [uber/tchannel#1426]
I tried to install tchannel node locally on mac using multiple node versions, 10-13. None of them works. I got the same error. I would like to use RingPop and tchannel is a dependency of it. Thanks!

npm install tchannel

> sse4_crc32@5.4.0 install /Users/congwang/node/node_modules/sse4_crc32
> node-gyp rebuild

  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
  LIBTOOL-STATIC Release/crc32c_sse42.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/crc32c_sse42.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/congwang/node/node_modules/sse4_crc32
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sse4_crc32@5.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sse4_crc32@5.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/congwang/.npm/_logs/2019-12-11T23_30_29_987Z-debug.log

**Comment by Raynos** [comment]
I pushed a branch called `node12` where I verified tchannel against both node 10 & node 12.

https://github.com/Raynos/tchannel-node/tree/node12

I recommend you maintain a fork of `tchannel` and `ringpop` and update both to be `node12` compatible.

The majority of tests pass on my branch, it's just updating binary dependencies to be compatible with newer versions of v8.
