### ISSUE TITLE
TChannel does not exit cleanly

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel#150]
When you call `channel.close()` tchannel still accepts incoming CallRequests.

Pr coming.

**Comment by Raynos** [comment]
More context:

```
/home/uber/autobahn/node_modules/tchannel/index.js:286
        throw new Error('cannot send() to destroyed tchannel'); // TODO typed
              ^
Error: cannot send() to destroyed tchannel
    at TChannel.send [as request] (/home/uber/autobahn/node_modules/tchannel/index.js:286:15)
    at TChannel.send (/home/uber/autobahn/node_modules/tchannel/index.js:278:20)
    at sendOrLocalPlain (/home/uber/autobahn/core/forward/index.js:83:18)
    at ForwardNode.forwardRequest (/home/uber/autobahn/core/forward/index.js:36:5)
    at onArg2 (/home/uber/autobahn/endpoints/forward.js:109:21)
    at SafeParseCallback (/home/uber/autobahn/node_modules/safe-json-parse/callback.js:17:5)
    at forward (/home/uber/autobahn/endpoints/forward.js:75:9)
    at TChannelServerOp.tchannelEndpoint [as handler] (/home/uber/autobahn/server/lib/tchannel-raw-handler.js:14:9)
    at runHandler (/home/uber/autobahn/node_modules/tchannel/index.js:764:14)
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by Raynos** [comment]
It's a known issue that `channel.close()` is not graceful.
