### ISSUE TITLE
[python] unrecognized endpoints need to return an application error

### ISSUE THREAD

**Issue by blampe** [uber/tchannel#232]
Hitting an endpoint that's not defined will currently time out and cause this error in the server:
```
$ python examples/tchannel_server.py --listen 8888
Inbound Server handle stream
Received request from 127.0.0.1:61333
Waiting for TChannel handshake...
Successfully completed handshake with /Users/blampe/src/tchannel/python/env/bin/tcurl.py[8765]
ERROR:tornado.application:exception calling callback <function handle at 0x10593b410> for <tornado.concurrent.Future object at 0x105f73e90>
Traceback (most recent call last):
  File "/Users/blampe/src/tchannel/python/env/lib/python2.7/site-packages/tornado-4.1-py2.7-macosx-10.9-x86_64.egg/tornado/concurrent.py", line 290, in _set_done
    cb(self)
  File "/Users/blampe/src/tchannel/python/tchannel/tornado/connection.py", line 147, in handle
    handler(f.result(), self)
  File "/Users/blampe/src/tchannel/python/tchannel/tornado/inbound_server.py", line 51, in preprocess_request
    self.req_handler.handle_request(context, conn)
  File "/Users/blampe/src/tchannel/python/tchannel/handler.py", line 49, in handle_request
    raise NotImplementedError()
NotImplementedError
```

**Comment by mmihic** [comment]
The server should probably return an Error frame with code bad-request (0x06) when this happens.

**Comment by jcorbin** [comment]
Currently the node implementation returns an application level error (call res code 1) for this: https://github.com/uber/tchannel/blob/master/node/endpoint-handler.js#L78

**Comment by mmihic** [comment]
That seems wrong?  An application-level error code indicates that it made it into application code.  In my mind, bad-request was for saying "I never handed this off to the application because there was something about it that was wrong".

**Comment by jcorbin** [comment]
Agree @mmihic --> #237

**Comment by junchaowu** [comment]
done
