### ISSUE TITLE
Node:  Request handler throws TypeError when there is no hostPort

### ISSUE THREAD

**Issue by Willyham** [uber/tchannel#696]
I probably have some tracer misconfiguration. If that is the case then this should be caught further up the stack and at instantiation time, rather than crashing when handling a request.

```
2015-06-11T12:46:04.872Z - fatal: swingline.development.localhost Uncaught Exception: non_object_property_call stack=TypeError: Cannot call method 'split' of null
    at Agent.setupNewSpan (/home/willy/Projects/orion/goodwill/node_modules/tchannel/trace/agent.js:63:44)
    at new TChannelInRequest (/home/willy/Projects/orion/goodwill/node_modules/tchannel/in_request.js:57:36)
    at TChannelV2Handler.buildInRequest (/home/willy/Projects/orion/goodwill/node_modules/tchannel/v2/handler.js:618:16)
    at TChannelV2Handler.handleCallRequest (/home/willy/Projects/orion/goodwill/node_modules/tchannel/v2/handler.js:191:20)
    at TChannelV2Handler.handleFrame (/home/willy/Projects/orion/goodwill/node_modules/tchannel/v2/handler.js:125:25)
    at TChannelConnection.handleReadFrame (/home/willy/Projects/orion/goodwill/node_modules/tchannel/connection.js:231:18)
    at ReadMachine.handleReadFrame [as emit] (/home/willy/Projects/orion/goodwill/node_modules/tchannel/connection.js:174:14)
    at ReadMachine.seek (/home/willy/Projects/orion/goodwill/node_modules/tchannel/node_modules/bufrw/stream/read_machine.js:120:14)
    at ReadMachine.handleChunk (/home/willy/Projects/orion/goodwill/node_modules/tchannel/node_modules/bufrw/stream/read_machine.js:67:28)
    at Socket.onSocketChunk (/home/willy/Projects/orion/goodwill/node_modules/tchannel/connection.js:93:19)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21), message=Cannot call method 'split' of null, _hostname=localhost.localdomain, _pid=27314
Aborted (core dumped)
```

**Comment by jcorbin** [comment]
cc @Raynos @rf 

Okay, so after investigating this it is arguably a "regression" since:
- ephemeral clients should be able to get incoming requests
- the tracing code should gracefully degrade / handle the ephemeral client case

What's going on here is that @Willyham's use case wasn't calling `chan.listen()`, so he was only getting incoming requests over his one (maybe only) outgoing connection into the hyperbahn.

I'm not sure exactly what was going on from a hyperbahn side here, thoughts:
- registering with an ephemeral channel should break early and loudly
- if an/all exit nodes can't connect back to a registered service instance, we should at least error loudly back to that service, if not find some way to evict / terminate any connections from / to the offending instance(s)
