### ISSUE TITLE
HyperbahnClient: advertisement failure, marking server as sick

### ISSUE THREAD

**Issue by nhattanmai** [uber/tchannel#958]
Hi,
I have problem when run example keyvalue. I think the problem is server working behind a proxy server. How to fix it or can run in local machine without proxy? Thanks very much. 

KEYVALUE ERROR: HyperbahnClient: advertisement failure, marking server as sick ~ { error: 
   { [TchannelSocketError: tchannel socket error (ECONNREFUSED from connect): connect ECONNREFUSED]
     type: 'tchannel.socket',
     message: 'tchannel socket error (ECONNREFUSED from connect): connect ECONNREFUSED',
     hostPort: '192.168.133.18:33922',
     direction: 'out',
     remoteAddr: null,
     name: 'TchannelSocketError',
     socketRemoteAddr: '127.0.0.1:21301',
     causeMessage: 'connect ECONNREFUSED',
     origMessage: 'connect ECONNREFUSED',
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     fullType: 'tchannel.socket~!~error.wrapped-io.connect.ECONNREFUSED' },
  serviceName: 'keyvalue',
  hostPort: undefined }
/home/tanmn2/Workspace/tchannel/node/node_modules/debug-logtron/backends/debug-log-backend.js:144
        throw new Error(logRecord.msg);
              ^
Error: HyperbahnClient: advertisement failure, marking server as sick
    at DebugLogStream.write (/home/tanmn2/Workspace/tchannel/node/node_modules/debug-logtron/backends/debug-log-backend.js:144:15)
    at DebugLogtron._log (/home/tanmn2/Workspace/tchannel/node/node_modules/debug-logtron/index.js:26:18)
    at DebugLogtron.error (/home/tanmn2/Workspace/tchannel/node/node_modules/debug-logtron/index.js:50:10)
    at advertiseInternalCb (/home/tanmn2/Workspace/tchannel/node/hyperbahn/index.js:310:58)
    at onResponse (/home/tanmn2/Workspace/tchannel/node/as/json.js:122:20)
    at DefinedEvent.onError [as listener] (/home/tanmn2/Workspace/tchannel/node/request.js:127:9)
    at DefinedEvent.emit (/home/tanmn2/Workspace/tchannel/node/lib/event_emitter.js:86:14)
    at TChannelRequest.emitError (/home/tanmn2/Workspace/tchannel/node/request.js:94:21)
    at onIdentified (/home/tanmn2/Workspace/tchannel/node/request.js:191:25)
    at Array.onConnectionClose (/home/tanmn2/Workspace/tchannel/node/peer.js:219:9)

**Comment by Raynos** [comment]
@nhattanmai 

If you are at uber you need to follow the instructions on how to run hyperbahn locally.

If your outside of uber you need to "write" hyperbahn. Hyperbahn is only partially open source. 
We have a hyperbahn cluster in our tests ( https://github.com/uber/tchannel/blob/master/node/test/lib/hyperbahn-cluster.js ) which is the closest thing to our internal hyperbahn cluster.
